<?php

namespace CPTools\Transformer;

/**
 * Test class for LoopTransformer.
 * Generated by PHPUnit on 2013-09-275 at 14:00:32.
 */
class LoopTransformerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Transformer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Transformer(array(
            'loop'  => array(
                array(
                    'name' => 'name1',
                    'value' => 'value1',
                    'value2'=> 'otherVal1'
                ),
                array(
                    'name' => 'name2',
                    'value' => 'value2',
                    'value2'=> 'otherVal2'
                ),
                array(
                    'name' => 'name3',
                    'value' => 'value3',
                    'value2'=> 'otherVal3'
                ),
            )
        ));
    }

    /**
     * Test Loop Transform
     */
    public function testTransform() {
        $lrLoopTransformer = new Transformers\LoopTransformer('loop');
        $lrLoopTransformer->addTransformer(new Transformers\RemoveKeyTransformer('name'));
        
        $this->object->addTransformer($lrLoopTransformer);
        $ltResult = $this->object->transform();
        
        $this->assertTrue(array_key_exists('loop', $ltResult));
        $this->assertFalse(array_key_exists('name', $ltResult['loop'][0]));
        $this->assertTrue(array_key_exists('value', $ltResult['loop'][0]));
    }
    
}
